# Generated by Django 4.0.3 on 2024-03-07 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_seats', models.IntegerField()),
                ('booked_seats', models.IntegerField()),
            ],
            options={
                'db_table': 'Seat',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Stops',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=100)),
                ('user_age', models.IntegerField()),
                ('user_email', models.EmailField(max_length=100)),
                ('user_picture', models.ImageField(upload_to='')),
                ('user_address', models.TextField(max_length=1000)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('fare_id', models.AutoField(primary_key=True, serialize=False)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_destination', to='projectApp.stop')),
                ('source_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_source', to='projectApp.stop')),
            ],
            options={
                'db_table': 'Fare',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(max_length=100)),
                ('bus_source', models.CharField(max_length=100)),
                ('bus_destination', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('destination_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_destination_stop', to='projectApp.stop')),
                ('seats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.seat')),
                ('source_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_source_stop', to='projectApp.stop')),
                ('stops', models.ManyToManyField(to='projectApp.stop')),
            ],
            options={
                'db_table': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.IntegerField()),
                ('booking_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.bus')),
                ('destination_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_destination_stop', to='projectApp.stop')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.seat')),
                ('source_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_source_stop', to='projectApp.stop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectApp.user')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
