# Generated by Django 4.0.3 on 2024-03-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
