# Generated by Django 4.0.3 on 2024-03-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_alter_user_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_destination',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_source',
        ),
    ]
