# Generated by Django 4.0.3 on 2024-03-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0004_alter_seat_booked_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='seats',
        ),
        migrations.AddField(
            model_name='bus',
            name='seats',
            field=models.ManyToManyField(null=True, to='projectApp.seat'),
        ),
    ]
