# Generated by Django 4.0.3 on 2024-03-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0005_remove_bus_seats_bus_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seats',
            field=models.ManyToManyField(to='projectApp.seat'),
        ),
    ]
