# Generated by Django 4.0.3 on 2024-03-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0007_alter_user_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
