# Generated by Django 4.0.3 on 2024-03-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0008_alter_user_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boarddroppoints',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BoardDropPoints',
            },
        ),
        migrations.AddField(
            model_name='stop',
            name='points',
            field=models.ManyToManyField(to='projectApp.boarddroppoints'),
        ),
    ]
