# Generated by Django 4.0.3 on 2024-03-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0010_rename_stop_id_boarddroppoints_point_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarddroppoints',
            name='stop',
        ),
        migrations.AddField(
            model_name='boarddroppoints',
            name='stop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectApp.stop'),
        ),
    ]
