# Generated by Django 4.0.3 on 2024-03-21 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0011_remove_boarddroppoints_stop_boarddroppoints_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boarddroppoints',
            name='stop',
        ),
        migrations.AddField(
            model_name='stop',
            name='points',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projectApp.boarddroppoints'),
        ),
    ]
