# Generated by Django 4.0.3 on 2024-03-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0012_remove_boarddroppoints_stop_stop_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='points',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bdpoints', to='projectApp.boarddroppoints'),
        ),
    ]
