# Generated by Django 4.0.3 on 2024-03-24 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0014_alter_stop_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='points',
        ),
        migrations.DeleteModel(
            name='Boarddroppoints',
        ),
    ]
